export const CartActionTypes = {
  TOGGLE_HIDE_CART_DROPDOWN: "TOGGLE_HIDE_CART_DROPDOWN",
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  RENOVE_ITEM: 'RENOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART'
};
